"""Verify the virtual-cable route, with explicit endpoint ids.

The route this measures is the one the Windows routing milestone documents:

    applications -> CABLE Input (playback side)
                 -> CABLE Output (recording side)
                 -> LowEnd capture (eCapture, loopback off)
                 -> Source/Core DSP
                 -> the physical output endpoint named on the command line

Every id is given explicitly. Nothing here uses "the first output" or "the OS
default output": the point of the route is that the OS default output is the
cable, so a check that plays to the default would be measuring the wrong thing.
The existing scripts/check-windows-render-landing.py picks outputs[0]/outputs[1]
and plays through winsound, which writes to the default endpoint - that check is
kept as it is, and it does not prove anything about a cable.

Both halves of the measurement are independent of the engine's own statistics:
the test signal is generated by `--play-tone` into the named cable playback
endpoint, and the result is observed through the *destination output endpoint's
own loopback* (`--monitor --capture-device <destination> --dump-wav <file>`).
A capture-side peak or a post-DSP peak inside the engine would only prove the
engine's own opinion of its output.

Fixed acceptance criteria, decided before any run rather than after one:

  level_off      the destination's loopback carries nothing while the engine is
                 stopped: peak < 0.02. A signal here means a bypass or duplicate
                 path exists (Windows' "listen to this device", or an app playing
                 to the destination as well), which is investigated, not excused.
  level_bypass   with the documented bypass (-model clean -intensity 0 -body 0
                 -output 0 -spatial off) the destination shows 0.5x..1.05x of the
                 0.40 tone amplitude: the route passes audio through and nothing
                 in it silently attenuates or doubles the signal.
  level_circuit  with the default Circuit model the destination shows at most
                 0.90x of the bypass level (documented attenuation) and at least
                 0.02: the DSP is in the path.
  channels       both channels carry the tone in every run that has signal
                 (peak_l >= 0.02 and peak_r >= 0.02). A single-channel or
                 swapped source fails; a swap alone cannot be seen from levels,
                 which is stated as a limit rather than asserted.
  pitch          the dominant frequency of the observed signal is within 10 Hz of
                 440 Hz in every run that has signal. A stream replayed at the
                 wrong rate lands tens of Hz away (44.1k -> 48k gives 479 Hz,
                 48k -> 44.1k gives 404 Hz).

Human listening is NOT part of this check and is not claimed by it: this is the
digital path at the destination endpoint's loopback.

Usage:
  python scripts/check-windows-cable-route.py <lowend_windows.exe> \
      --cable-playback <render endpoint id of the cable> \
      --cable-recording <capture endpoint id of the cable> \
      --output <physical output endpoint id>
  python scripts/check-windows-cable-route.py --self-check

Missing hardware is reported as SKIPPED, which is not a pass. A run that
observes something contradicting a criterion above is FAILED.
"""
import argparse
import math
import pathlib
import re
import signal
import struct
import subprocess
import sys
import tempfile
import time
import wave

# Fixed signal, matching the CLI's --play-tone.
TONE_HZ = 440.0
TONE_AMPLITUDE = 0.4
TONE_SECONDS = 3
MONITOR_SECONDS = 5
DESTINATION_SETTLE_SECONDS = 1.0

# Decided before the runs; see the module docstring.
LEVEL_OFF_MAX = 0.02
BYPASS_MIN_RATIO = 0.50
BYPASS_MAX_RATIO = 1.05
CIRCUIT_MAX_RATIO = 0.90
CHANNEL_MIN_PEAK = 0.02
PITCH_TOLERANCE_HZ = 10.0

# The bypass has to be the documented one, including the stages that are off by
# default: spatial and output conditioning are part of what "bypass" means, so
# they are named here instead of being left to the defaults.
BYPASS_ARGS = ["--model", "clean", "--intensity", "0", "--body", "0", "--output", "0",
               "--spatial", "off"]


class CheckFailure(Exception):
    """A criterion was observed to fail. Never raised for missing hardware."""


class CheckSkipped(Exception):
    """The hardware needed for this check is not present."""


# ─── Signal analysis ──────────────────────────────────────────────────

def read_wav(path: pathlib.Path):
    """Returns (rate, channels, left, right) as float lists scaled to [-1, 1)."""
    with wave.open(str(path), "rb") as handle:
        rate = handle.getframerate()
        channels = handle.getnchannels()
        width = handle.getsampwidth()
        frames = handle.readframes(handle.getnframes())
    if width != 2:
        raise CheckFailure(f"the capture dump is {width * 8}-bit; this checker reads 16-bit PCM")
    samples = struct.unpack("<%dh" % (len(frames) // 2), frames)
    scale = 1.0 / 32768.0
    left = [samples[i] * scale for i in range(0, len(samples), channels)]
    right = [samples[i + 1] * scale for i in range(0, len(samples) - 1, channels)] \
        if channels > 1 else list(left)
    return rate, channels, left, right


def peak(values):
    return max((abs(v) for v in values), default=0.0)


def dominant_frequency(values, rate, low=200.0, high=800.0, step=2.0):
    """Frequency with the largest Goertzel magnitude in [low, high]."""
    if not values:
        return None
    # One pass per candidate is fine for a few seconds of audio and keeps the
    # measurement independent of how the samples are windowed.
    best_frequency = None
    best_magnitude = -1.0
    count = len(values)
    frequency = low
    while frequency <= high:
        omega = 2.0 * math.pi * frequency / rate
        coefficient = 2.0 * math.cos(omega)
        s1 = 0.0
        s2 = 0.0
        for value in values:
            s0 = value + coefficient * s1 - s2
            s2 = s1
            s1 = s0
        magnitude = (s1 * s1 + s2 * s2 - coefficient * s1 * s2) / (count * count)
        if magnitude > best_magnitude:
            best_magnitude = magnitude
            best_frequency = frequency
        frequency += step
    return best_frequency


def analyze(dump: pathlib.Path):
    rate, channels, left, right = read_wav(dump)
    # The first half second is skipped: a stream that just started still contains
    # the render endpoint's priming silence, and measuring it would understate the
    # level of a run that is otherwise fine.
    skip = int(rate * 0.5)
    left = left[skip:]
    right = right[skip:]
    return {
        "rate": rate,
        "channels": channels,
        "peak_left": peak(left),
        "peak_right": peak(right),
        "peak": max(peak(left), peak(right)),
        "frequency": dominant_frequency(left, rate),
        "frames": len(left),
    }


def judge_case(label, measured, *, expect_silence=False, reference_bypass=None):
    """Returns a list of problem strings for one measured run."""
    problems = []
    if expect_silence:
        if measured["peak"] >= LEVEL_OFF_MAX:
            problems.append(
                f"{label}: the destination carried peak {measured['peak']:.6f} while the "
                f"engine was stopped (limit {LEVEL_OFF_MAX:.2f}); a bypass or duplicate "
                f"path is feeding the output, so investigate before trusting any other run")
        return problems

    if measured["frames"] <= 0:
        problems.append(f"{label}: the destination delivered no frames at all")
        return problems
    if measured["peak"] < CHANNEL_MIN_PEAK:
        problems.append(
            f"{label}: the destination only reached peak {measured['peak']:.6f}; the "
            f"processed audio is not arriving at a usable level")
    if measured["peak_left"] < CHANNEL_MIN_PEAK or measured["peak_right"] < CHANNEL_MIN_PEAK:
        problems.append(
            f"{label}: one channel carried no tone (L {measured['peak_left']:.6f}, "
            f"R {measured['peak_right']:.6f}); the routed signal is not a stereo copy of "
            f"the source")
    if measured["frequency"] is None:
        problems.append(f"{label}: the observed signal had no measurable frequency")
    elif abs(measured["frequency"] - TONE_HZ) > PITCH_TOLERANCE_HZ:
        problems.append(
            f"{label}: the destination's dominant frequency is {measured['frequency']:.0f} Hz, "
            f"not {TONE_HZ:.0f} +/- {PITCH_TOLERANCE_HZ:.0f} Hz; the stream is being replayed "
            f"at the wrong rate")

    if reference_bypass is not None:
        ratio = measured["peak"] / reference_bypass["peak"] if reference_bypass["peak"] else 0.0
        if ratio >= CIRCUIT_MAX_RATIO:
            problems.append(
                f"{label}: the Circuit run landed at {ratio:.2f}x of the bypass run, above "
                f"the {CIRCUIT_MAX_RATIO:.2f}x bound; the DSP did not apply its documented "
                f"attenuation")
    else:
        ratio = measured["peak"] / TONE_AMPLITUDE
        if ratio < BYPASS_MIN_RATIO or ratio > BYPASS_MAX_RATIO:
            problems.append(
                f"{label}: the bypass run reached {ratio:.2f}x of the {TONE_AMPLITUDE:.2f} "
                f"source amplitude, outside {BYPASS_MIN_RATIO:.2f}x..{BYPASS_MAX_RATIO:.2f}x; "
                f"the route does not pass the signal through unchanged")
    return problems


# ─── Process control ──────────────────────────────────────────────────

def list_devices(executable: pathlib.Path):
    result = subprocess.run([str(executable), "--list-devices"],
                            capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        raise CheckSkipped(f"--list-devices failed: {result.stderr.strip()}")
    return result.stdout


def parse_outputs(text):
    ids = []
    in_outputs = False
    for line in text.splitlines():
        if line.startswith("Output devices"):
            in_outputs = True
            continue
        if line.startswith("Input devices"):
            in_outputs = False
            continue
        if in_outputs:
            match = re.search(r"id=(\{[^}]*\}\.\{[^}]*\})", line)
            if match:
                ids.append((match.group(1), line.strip()))
    return ids


def parse_inputs(text):
    ids = []
    in_inputs = False
    for line in text.splitlines():
        if line.startswith("Input devices"):
            in_inputs = True
            continue
        if line.startswith("Virtual cables") or line.startswith("* marks"):
            in_inputs = False
            continue
        if in_inputs:
            match = re.search(r"id=(\{[^}]*\}\.\{[^}]*\})", line)
            if match:
                ids.append((match.group(1), line.strip()))
    return ids


def parse_cable_pairs(text):
    pairs = []
    playback = None
    for line in text.splitlines():
        match = re.search(r"^\s*playback\s+id=(\S+)", line)
        if match:
            playback = match.group(1)
        match = re.search(r"^\s*recording\s+id=(\S+)", line)
        if match and playback is not None:
            pairs.append((playback, match.group(1)))
            playback = None
    return pairs


def start(executable: pathlib.Path, args):
    return subprocess.Popen([str(executable), *args], stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, text=True,
                            creationflags=getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0))


def stop(process, seconds: float = 0.0):
    """Stops a started process and always reaps it, even after a timeout."""
    if process is None:
        return "", ""
    if seconds:
        time.sleep(seconds)
    if process.poll() is None:
        try:
            process.send_signal(signal.CTRL_BREAK_EVENT)
        except Exception:
            process.terminate()
    try:
        return process.communicate(timeout=30)
    except subprocess.TimeoutExpired:
        process.kill()
        return process.communicate()


def run_case(executable, label, engine_args, ids, dump):
    """Runs one measurement: optional engine, tone into the cable, observe the output."""
    engine = None
    monitor = None
    try:
        if engine_args is not None:
            engine = start(executable, engine_args)
            time.sleep(DESTINATION_SETTLE_SECONDS)
            if engine.poll() is not None:
                out, err = engine.communicate()
                raise CheckFailure(f"{label}: the engine exited before the tone started:\n"
                                   f"{out}\n{err}")
        monitor = start(executable, ["--monitor", str(MONITOR_SECONDS),
                                     "--capture-device", ids["output"],
                                     "--dump-wav", str(dump)])
        time.sleep(0.5)
        tone = subprocess.run([str(executable), "--play-tone", str(TONE_SECONDS),
                               "--device", ids["cable_playback"]],
                              capture_output=True, text=True, timeout=TONE_SECONDS + 60)
        if tone.returncode != 0:
            raise CheckFailure(f"{label}: --play-tone failed: {tone.stdout}\n{tone.stderr}")
    finally:
        monitor_out, monitor_err = stop(monitor, MONITOR_SECONDS + 1.5)
        engine_out, engine_err = stop(engine)

    for name, text in (("engine", engine_out + engine_err),
                       ("monitor", monitor_out + monitor_err)):
        errors = re.findall(r"^\s*(Capture errors|Render errors)\s+(\d+)", text, re.M)
        if any(int(value) != 0 for _, value in errors):
            raise CheckFailure(f"{label}: the {name} reported device errors: {errors}")
    if not dump.exists():
        raise CheckFailure(f"{label}: no capture dump was written, so nothing was observed")
    return analyze(dump)


# ─── Self-check (no hardware) ─────────────────────────────────────────

def write_tone(path: pathlib.Path, frequency: float, amplitude: float,
               seconds: float, right_only: bool = False) -> None:
    rate = 48000
    frames = bytearray()
    for i in range(int(rate * seconds)):
        sample = int(amplitude * 32767 * math.sin(2.0 * math.pi * frequency * i / rate))
        left = 0 if right_only else sample
        frames += struct.pack("<hh", left, sample)
    with wave.open(str(path), "w") as handle:
        handle.setnchannels(2)
        handle.setsampwidth(2)
        handle.setframerate(rate)
        handle.writeframes(bytes(frames))


def self_check() -> int:
    """Proves the checker discriminates, using signals it generates itself.

    Without this, a checker that never fails would look identical to a route that
    always passes. Each case below must produce exactly the verdict it is named
    for; the fixed criteria are the same ones the device run uses.
    """
    problems = []
    with tempfile.TemporaryDirectory() as scratch:
        scratch = pathlib.Path(scratch)

        good = scratch / "good.wav"
        write_tone(good, TONE_HZ, TONE_AMPLITUDE, 1.0)
        measured = analyze(good)
        if measured["frequency"] is None or abs(measured["frequency"] - TONE_HZ) > 1.0:
            problems.append(
                f"a {TONE_HZ:.0f} Hz tone measured {measured['frequency']} Hz")
        if measured["peak"] < TONE_AMPLITUDE * 0.9:
            problems.append(f"a {TONE_AMPLITUDE:.2f} tone measured peak {measured['peak']:.6f}")

        detuned = scratch / "detuned.wav"
        # What a 48 kHz stream played at 44.1 kHz looks like: 440 Hz lands at
        # 404 Hz. The pitch criterion must reject it.
        write_tone(detuned, 404.0, TONE_AMPLITUDE, 1.0)
        detuned_result = analyze(detuned)
        if not judge_case("detuned", detuned_result):
            problems.append("a 404 Hz signal passed the 440 Hz pitch criterion")
        if abs((detuned_result["frequency"] or 0.0) - 404.0) > 2.0:
            problems.append(
                f"a 404 Hz signal measured {detuned_result['frequency']} Hz")

        one_channel = scratch / "right-only.wav"
        write_tone(one_channel, TONE_HZ, TONE_AMPLITUDE, 1.0, right_only=True)
        if not any("one channel" in problem
                   for problem in judge_case("right-only", analyze(one_channel))):
            problems.append("a right-channel-only signal passed the channel criterion")

        silent = scratch / "silence.wav"
        write_tone(silent, TONE_HZ, 0.0, 1.0)
        silent_result = analyze(silent)
        if judge_case("silence", silent_result, expect_silence=True):
            problems.append("a silent file failed the 'nothing rendering' criterion")
        if not judge_case("silence-loud", silent_result):
            problems.append("a silent file passed the 'signal present' criteria")

        quiet = scratch / "quiet.wav"
        write_tone(quiet, TONE_HZ, 0.30, 1.0)
        # 0.30 into a 0.40 bypass expectation is 0.75x of the source: inside the
        # band, so the band must accept it.
        if judge_case("quiet-bypass", analyze(quiet)):
            problems.append("a 0.75x bypass ratio was rejected as out of band")
        # The same 0.30 against a 0.40 bypass reference is 0.75x, which is
        # *below* the Circuit bound, so the attenuation criterion accepts it (the
        # DSP did attenuate). The case that must be rejected is a Circuit run that
        # barely attenuated: 0.38 against the same reference is 0.95x.
        unattenuated = scratch / "unattenuated.wav"
        write_tone(unattenuated, TONE_HZ, 0.38, 1.0)
        if judge_case("quiet-circuit", analyze(quiet),
                      reference_bypass={"peak": TONE_AMPLITUDE}):
            problems.append("an attenuated Circuit run (0.75x of its bypass reference) was "
                            "rejected by the criteria")
        if not any("attenuation" in problem
                   for problem in judge_case("unattenuated-circuit",
                                             analyze(unattenuated),
                                             reference_bypass={"peak": 0.38})):
            problems.append("an unattenuated Circuit run (1.00x of its bypass reference) "
                            "passed the attenuation bound")

    if problems:
        for problem in problems:
            print(f"  FAIL: {problem}", file=sys.stderr)
        return 1
    print("checker self-check passed: the level, channel and pitch criteria accept the "
          "signal they describe and reject silence, a single-channel source, a "
          "detuned stream and an unattenuated Circuit run.")
    return 0


# ─── Device run ───────────────────────────────────────────────────────

def device_run(args) -> int:
    executable = pathlib.Path(args.executable).resolve(strict=True)
    ids = {
        "cable_playback": args.cable_playback,
        "cable_recording": args.cable_recording,
        "output": args.output,
    }

    listing = list_devices(executable)
    outputs = dict(parse_outputs(listing))
    inputs = dict(parse_inputs(listing))
    pairs = parse_cable_pairs(listing)

    for key, table, described in (("cable_playback", outputs, "output endpoint"),
                                  ("cable_recording", inputs, "input endpoint"),
                                  ("output", outputs, "output endpoint")):
        if ids[key] not in table:
            raise CheckSkipped(
                f"the {described} given for {key.replace('_', ' ')} is not present on this "
                f"machine ({ids[key]}); nothing was measured. This is not a pass.")

    if (ids["cable_playback"], ids["cable_recording"]) not in pairs:
        raise CheckSkipped(
            "the two endpoints given as the cable are not paired as one virtual device by "
            "the CLI's own --list-devices report, so the cable route was not verified. "
            "This is not a pass.")

    print("route under test:")
    print(f"  cable playback   {outputs[ids['cable_playback']][:70]}")
    print(f"  cable recording  {inputs[ids['cable_recording']][:70]}")
    print(f"  output           {outputs[ids['output']][:70]}")
    print(f"signal: {TONE_HZ:.0f} Hz stereo at amplitude {TONE_AMPLITUDE:.2f} for "
          f"{TONE_SECONDS} s, played by --play-tone into the cable playback endpoint")
    print(f"observed: the output endpoint's own loopback for {MONITOR_SECONDS} s\n")
    sys.stdout.flush()

    problems = []
    with tempfile.TemporaryDirectory() as scratch:
        scratch = pathlib.Path(scratch)

        off = run_case(executable, "engine off", None, ids, scratch / "off.wav")
        print(f"engine off:      peak={off['peak']:.6f} frames={off['frames']}")
        problems += judge_case("engine off", off, expect_silence=True)

        bypass = run_case(executable, "bypass",
                          ["--input-device", ids["cable_recording"],
                           "--device", ids["output"], *BYPASS_ARGS],
                          ids, scratch / "bypass.wav")
        print(f"clean bypass:    peak={bypass['peak']:.6f} "
              f"(L {bypass['peak_left']:.6f}, R {bypass['peak_right']:.6f}) "
              f"freq={bypass['frequency']} frames={bypass['frames']}")
        problems += judge_case("clean bypass", bypass)

        circuit = run_case(executable, "circuit",
                           ["--input-device", ids["cable_recording"],
                            "--device", ids["output"]],
                           ids, scratch / "circuit.wav")
        ratio = circuit["peak"] / bypass["peak"] if bypass["peak"] else 0.0
        print(f"circuit:         peak={circuit['peak']:.6f} "
              f"(L {circuit['peak_left']:.6f}, R {circuit['peak_right']:.6f}) "
              f"freq={circuit['frequency']} frames={circuit['frames']} ({ratio:.2f}x bypass)")
        problems += judge_case("circuit", circuit, reference_bypass=bypass)

    if problems:
        for problem in problems:
            print(f"  MISMATCH: {problem}", file=sys.stderr)
        return 1

    print("\ncable route verified: the tone played into the cable's playback endpoint reached "
          "the named output endpoint only while the engine was running, with both channels "
          "carrying it at 440 Hz, and the Circuit model attenuated it relative to the "
          "documented bypass.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify the virtual-cable route with explicit endpoint ids.")
    parser.add_argument("executable", nargs="?",
                        help="path to lowend_windows.exe")
    parser.add_argument("--cable-playback", help="render endpoint id of the cable's playback side")
    parser.add_argument("--cable-recording", help="capture endpoint id of the cable's recording side")
    parser.add_argument("--output", help="physical output endpoint id to observe")
    parser.add_argument("--self-check", action="store_true",
                        help="verify this checker against signals it generates; needs no device")
    args = parser.parse_args()

    if args.self_check:
        return self_check()
    if not args.executable or not args.cable_playback or not args.cable_recording or not args.output:
        parser.error("give the executable, --cable-playback, --cable-recording and --output, "
                     "or --self-check")

    try:
        return device_run(args)
    except CheckSkipped as skipped:
        print(f"SKIPPED: {skipped}")
        return 0
    except CheckFailure as failure:
        print(f"FAILED: {failure}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
